"""
Inference layer for the CWRU bearing-monitoring application.

This module mirrors the preprocessing used by notebooks/cwru_5channel.ipynb:

    raw 12-kHz signal -> order tracking -> EndToEndSTFTClassifier

The notebook checkpoints store `band_edges`, not `bandpass_low_hz` /
`bandpass_high_hz`. Those edges are used to reconstruct the exact multiband
filter bank inside the model.
"""
from __future__ import annotations

import glob
import os
from dataclasses import dataclass
from fractions import Fraction

import numpy as np
import torch
from scipy.signal import resample_poly

from model import EndToEndSTFTClassifier, ModelConfig

REFERENCE_RPM = 1797


def order_track_resample(
    signal: np.ndarray,
    actual_rpm: float,
    reference_rpm: float = REFERENCE_RPM,
) -> np.ndarray:
    """Match the notebook's order-tracking preprocessing exactly."""
    ratio = Fraction(reference_rpm, actual_rpm).limit_denominator(1000)
    if ratio.numerator == ratio.denominator:
        return signal
    return resample_poly(
        signal, ratio.numerator, ratio.denominator
    ).astype(np.float32)


@dataclass
class Prediction:
    label: str
    confidence: float
    probabilities: dict


class BearingEnsemble:
    """Load checkpoint files and average their recording-level probabilities."""

    def __init__(
        self,
        checkpoint_dir: str,
        config: ModelConfig | None = None,
        device: str | None = None,
    ):
        self.config = config or ModelConfig()
        self.device = torch.device(
            device or ("cuda" if torch.cuda.is_available() else "cpu")
        )
        self.models: list[EndToEndSTFTClassifier] = []
        self._load_checkpoints(checkpoint_dir)

    @staticmethod
    def _checkpoint_value(checkpoint, key, default):
        value = checkpoint.get(key, default)
        return value

    def _load_checkpoints(self, checkpoint_dir: str):
        paths = sorted(glob.glob(os.path.join(checkpoint_dir, "*.pt")))
        if not paths:
            raise FileNotFoundError(
                f"No .pt checkpoint files found in {checkpoint_dir}."
            )

        for path in paths:
            checkpoint = torch.load(path, map_location=self.device)

            # Checkpoints generated by cwru_5channel.ipynb contain `band_edges`.
            # Fall back to the model defaults only for older compatible files.
            band_edges = checkpoint.get(
                "band_edges", self.config.band_edges
            )

            # Prefer the checkpoint's architectural metadata when present.
            config = ModelConfig(
                num_classes=len(checkpoint.get("class_names", self.config.class_names)),
                class_names=tuple(
                    checkpoint.get("class_names", self.config.class_names)
                ),
                segment_length=int(
                    checkpoint.get("segment_length", self.config.segment_length)
                ),
                segment_hop=int(
                    checkpoint.get("segment_hop", self.config.segment_hop)
                ),
                n_fft=int(checkpoint.get("n_fft", self.config.n_fft)),
                stft_hop=int(
                    checkpoint.get("stft_hop", self.config.stft_hop)
                ),
                stft_win_length=int(
                    checkpoint.get(
                        "stft_win_length", self.config.stft_win_length
                    )
                ),
                window_chunk_size=self.config.window_chunk_size,
                fault_sample_rate_hz=self.config.fault_sample_rate_hz,
                bandpass_taps=self.config.bandpass_taps,
                band_edges=tuple(tuple(x) for x in band_edges),
                augment=self.config.augment,
                noise_std=self.config.noise_std,
                max_shift_fraction=self.config.max_shift_fraction,
                freq_mask_fraction=self.config.freq_mask_fraction,
                time_mask_fraction=self.config.time_mask_fraction,
            )

            model = EndToEndSTFTClassifier(
                config=config,
                band_edges=band_edges,
            ).to(self.device)
            model.load_state_dict(checkpoint["state_dict"])
            model.eval()
            self.models.append(model)

        print(
            f"Loaded {len(self.models)} ensemble member(s) from "
            f"{checkpoint_dir}"
        )

    @torch.no_grad()
    def predict(self, raw_signal: np.ndarray, rpm: float) -> Prediction:
        """Predict a bearing condition from a raw 12-kHz vibration buffer.

        The input is expected to be at the fault-condition sample rate (12 kHz)
        and NOT yet order-tracked. `rpm` is the actual shaft speed.
        """
        if len(raw_signal) < self.config.segment_length:
            raise ValueError(
                f"Need at least {self.config.segment_length} samples to predict; "
                f"got {len(raw_signal)}. Buffer more incoming samples first."
            )

        tracked = order_track_resample(raw_signal, actual_rpm=rpm)
        raw = torch.as_tensor(
            tracked, dtype=torch.float32, device=self.device
        ).unsqueeze(0)
        lengths = torch.as_tensor(
            [tracked.shape[0]], dtype=torch.long, device=self.device
        )

        probs_sum = None
        for model in self.models:
            log_probs = model(raw, lengths)
            probs = torch.exp(log_probs)
            probs_sum = probs if probs_sum is None else probs_sum + probs

        averaged = (
            probs_sum / len(self.models)
        ).squeeze(0).cpu().numpy()

        class_names = self.models[0].config.class_names
        best_idx = int(np.argmax(averaged))

        return Prediction(
            label=class_names[best_idx],
            confidence=float(averaged[best_idx]),
            probabilities={
                name: float(p)
                for name, p in zip(class_names, averaged)
            },
        )
